### ISSUE TITLE
origin-js: ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#1392]
Seen when running the discovery listener.

    ERROR ReferenceError: URL is not defined
        at parseSchemaId (/home/mike/dev/origin/origin-js/dist/origin.node.js:162774:13)
        at IpfsDataStore._callee$ (/home/mike/dev/origin/origin-js/dist/origin.node.js:163031:98)
        at tryCatch (/home/mike/dev/origin/origin-js/dist/origin.node.js:90514:40)
        at Generator.invoke [as _invoke] (/home/mike/dev/origin/origin-js/dist/origin.node.js:90740:22)
        at Generator.prototype.(anonymous function) [as next] (/home/mike/dev/origin/origin-js/dist/origin.node.js:90566:21)
        at asyncGeneratorStep (/home/mike/dev/origin/origin-js/dist/origin.node.js:162950:103)
        at _next (/home/mike/dev/origin/origin-js/dist/origin.node.js:162952:194)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

Appears to be [this line](https://github.com/OriginProtocol/origin/blob/master/origin-js/src/ipfsInterface/schema-id.js#L33) in origin-js, but it's not clear to me what `URL` is supposed to be.  urllib?  Or maybe node's `URL` class?

**Comment by mikeshultz** [comment]
Should be running v10.
