### ISSUE TITLE
Can't run on Windows

### ISSUE THREAD

**Issue by gladguy** [OriginProtocol/origin#203]
Getting error code ELIFECYCLE

```
900 silly saveTree   `-- watchpack@1.6.0
901 warn ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
902 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
903 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
904 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
904 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
904 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
904 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
905 verbose stack Error: scrypt@6.0.3 install: `node-gyp rebuild`
905 verbose stack Exit status 1
905 verbose stack     at EventEmitter.<anonymous> (C:\node-v10.1.0\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
905 verbose stack     at EventEmitter.emit (events.js:182:13)
905 verbose stack     at ChildProcess.<anonymous> (C:\node-v10.1.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
905 verbose stack     at ChildProcess.emit (events.js:182:13)
905 verbose stack     at maybeClose (internal/child_process.js:957:16)
905 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
906 verbose pkgid scrypt@6.0.3
907 verbose cwd F:\HelloToken.io\OriginProtocol\origin-demo-dapp
908 verbose Windows_NT 6.1.7601
909 verbose argv "C:\\node-v10.1.0\\node.exe" "C:\\node-v10.1.0\\node_modules\\npm\\bin\\npm-cli.js" "install"
910 verbose node v10.1.0
911 verbose npm  v5.6.0
912 error code ELIFECYCLE
913 error errno 1
914 error scrypt@6.0.3 install: `node-gyp rebuild`
914 error Exit status 1
915 error Failed at the scrypt@6.0.3 install script.
915 error This is probably not a problem with npm. There is likely additional logging output above.
916 verbose exit [ 1, true ]
```

**Comment by wanderingstan** [comment]
I think this is when running on Windows

**Comment by gladguy** [comment]
Yes it is on Windows

**Comment by wanderingstan** [comment]
Additional logs from @gladguy 
[2018-05-20T22_31_05_203Z-debug.log](https://github.com/OriginProtocol/demo-dapp/files/2022831/2018-05-20T22_31_05_203Z-debug.log)
[2018-05-20T22_25_53_269Z-debug.log](https://github.com/OriginProtocol/demo-dapp/files/2022832/2018-05-20T22_25_53_269Z-debug.log)
[2018-05-20T21_26_17_751Z-debug.log](https://github.com/OriginProtocol/demo-dapp/files/2022833/2018-05-20T21_26_17_751Z-debug.log)

**Comment by gaboesquivel** [comment]
See https://github.com/angular/angular/issues/13935

it seems fsevents should be indicated as optional and run `npm i --no-optional` or try `npm i -f`

**Comment by tomlinton** [comment]
I suspect this is probably resolved, but feel free to reopen if not @gladguy. You may also need to run `npm i -g --production windows-build-tools` on Windows prior to installing any Origin packages.
