### ISSUE TITLE
Event-listener fromBlock > toBlock error

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#2071]
Seen on staging:

`[ERROR] event-listener: Error: fromBlock > toBlock
    at pastEventBatcher (/app/packages/graphql/src/utils/eventCache.js:15:36)
    at getPastEvents (/app/packages/graphql/src/utils/eventCache.js:119:29)
    at Object.allEvents (/app/packages/graphql/src/utils/eventCache.js:153:11)
    at Promise.all.withRetrys (/app/infra/discovery/src/listener/listener.js:155:56)
    at withRetrys (/app/infra/discovery/src/listener/utils.js:69:20)
    at main (/app/infra/discovery/src/listener/listener.js:154:7)
    at process._tickCallback (internal/process/next_tick.js:68:7) 'will retry in 0.082 seconds, retry count 0'`

There are two issues here, one is the error, and one is the retry handler never actually retries. I think this should be resolved by #1975. See #1972.

**Comment by nick** [comment]
Fixed in #2116
