### ISSUE TITLE
GraphQL serivce issues/invalid provider response handling

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2458]
Seen these in the GraphQL service logs.  Probably invalid responses from Alchemy, but worth a look.

    Payload:  {"id":1560277183890532,"jsonrpc":"2.0","params":["0x792430",false],"method":"eth_getBlockByNumber"}
    TypeError: Cannot read property 'number' of null
        at toBufferBlock (/app/packages/graphql/node_modules/web3-provider-engine/index.js:218:50)
        at self._getBlockByNumber (/app/packages/graphql/node_modules/web3-provider-engine/index.js:59:27)
        at _handleAsync (/app/packages/graphql/node_modules/web3-provider-engine/index.js:139:12)
        at /app/packages/graphql/node_modules/web3-provider-engine/index.js:198:9
        at /app/node_modules/async/internal/once.js:12:16
        at replenish (/app/node_modules/async/internal/eachOfLimit.js:61:25)
        at /app/node_modules/async/internal/eachOfLimit.js:71:9
        at eachLimit (/app/node_modules/async/eachLimit.js:43:36)
        at /app/node_modules/async/internal/doLimit.js:9:16
        at end (/app/packages/graphql/node_modules/web3-provider-engine/index.js:175:5)
        at end (/app/packages/graphql/src/providers/ThrottleRPCProvider.js:125:9)

.

    Payload:  {"jsonrpc":"2.0","id":156978,"method":"eth_blockNumber","params":[]}
    TypeError: Cannot read property 'number' of null
        at toBufferBlock (/app/packages/graphql/node_modules/web3-provider-engine/index.js:218:50)
        at self._getBlockByNumber (/app/packages/graphql/node_modules/web3-provider-engine/index.js:59:27)
        at _handleAsync (/app/packages/graphql/node_modules/web3-provider-engine/index.js:139:12)
        at /app/packages/graphql/node_modules/web3-provider-engine/index.js:198:9
        at /app/node_modules/async/internal/once.js:12:16
        at replenish (/app/node_modules/async/internal/eachOfLimit.js:61:25)
        at /app/node_modules/async/internal/eachOfLimit.js:71:9
        at eachLimit (/app/node_modules/async/eachLimit.js:43:36)
        at /app/node_modules/async/internal/doLimit.js:9:16
        at end (/app/packages/graphql/node_modules/web3-provider-engine/index.js:175:5)
        at end (/app/packages/graphql/src/providers/ThrottleRPCProvider.js:125:9)

**Comment by mikeshultz** [comment]
This appears to be just invalid responses from Alchemy.  web3-provider-engine is not really defensive about processing responses for its new block event handler.

[It calls `toBufferBlock()` without checking that the response is sane](https://github.com/mikeshultz/web3-provider-engine/blob/origin-protocol/index.js#L59).

Not really sure this needs correcting.  It's probably not counted in our error stats since the error exists within this event handler and not in the subprovider chain, though.  But adding better error handling would require yet another change to web3-provider-engine diverging from the metamask master branch even further.

Think I want to close this was wontfix.  Thoughts, @franckc?

**Comment by franckc** [comment]
Yes, I think closing as wontfix is fine - I'd rather not diverge too much from metamask master branch... Thanks @mikeshultz for investigating.
