### ISSUE TITLE
Purse needs better error handling

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2477]
The JSON-RPC error handling in Purse is awful and it should be fixed before it reaches production use.  If a provider decides to fail for whatever reason, the relayer probably shouldn't crash.

**Comment by mikeshultz** [comment]
Will move the custom web3-provider-engine provider out of graphql into its own package so Purse can use it.

**Comment by mikeshultz** [comment]
Saw this with an `eth_getTransactionByHash` call.  Would be good to not kill the entire process when it happens.

    (node:82) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: "<h1>Server Error (500)</h1>"
        at Object.InvalidResponse (/app/node_modules/web3-core-helpers/src/errors.js:42:16)
        at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/src/index.js:73:32)
        at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:64:18)
        at XMLHttpRequest._setReadyState (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:354:12)
        at XMLHttpRequest._onHttpResponseEnd (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:509:12)
        at IncomingMessage.<anonymous> (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:469:24)
        at IncomingMessage.emit (events.js:203:15)
        at endReadableNT (_stream_readable.js:1129:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    (node:82) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:82) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mikeshultz** [comment]
bzzt, try again

    (node:78) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.15.5</center>\r\n</body>\r\n</html>\r\n"
        at Object.InvalidResponse (/app/node_modules/web3-core-helpers/src/errors.js:42:16)
        at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/src/index.js:73:32)
        at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:64:18)
        at XMLHttpRequest._setReadyState (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:354:12)
        at XMLHttpRequest._onHttpResponseEnd (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:509:12)
        at IncomingMessage.<anonymous> (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:469:24)
        at IncomingMessage.emit (events.js:203:15)
        at endReadableNT (_stream_readable.js:1129:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    (node:78) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:78) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mikeshultz** [comment]
Purse now has better error handling.
