### ISSUE TITLE
Messaging server error

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2523]
~~Possibly related to #2495, but the times don't really match up and it seems to be rare.~~  Not related to that issue.

    (node:155) UnhandledPromiseRejectionWarning: SequelizeUniqueConstraintError: Validation error
        at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:312:18)
        at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:71:18)
        at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:690:18)
        at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
        at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
        at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
    (node:155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or 
    by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Not clear what triggers this yet as the trace is all but useless.  It appears to show up immediately after a `recovered buffer` message but it only appears to have happened a few times on 5/28(logs only go back 30 days, however).

**Comment by mikeshultz** [comment]
The only table with an explicit unique constraint(not including primary keys) is `msg_conversation`:

    "msg_conversation_external_id_key" UNIQUE CONSTRAINT, btree (external_id)

This could occur in an extreme edge case in a [race condition between these two lines](https://github.com/OriginProtocol/origin/blob/master/infra/messaging/src/index.js#L197-L223) but it would require the well-behaved client to fire off essentially simultaneous requests to cause this and for node to just happen to block right on the `BEGIN` transaction.  Not impossible, but unlikely.

Could be a pirmary key error.  Probably not `msg_conversee` since that's only created during a conversation creation(unless someone tries and is able to send a message to oneself).  Probably not `msg_registry` as that's always an upsert.  Definitely not `msg_conversation` since it's a serial. So....

**Comment by mikeshultz** [comment]
I have successfully triggered this on staging by trying to message myself.

**Comment by franckc** [comment]
Thanks for investigating this error. Agreed with suggested resolution. P3 also seems appropriate priority.
