### ISSUE TITLE
Purse: known transaction

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2527]
Seen on staging:

    [WARN]  relayer: Transaction 0x33aa247d292c1a41ffda4e219e243c5ea9f3ce647081481bc501a39f143a21ff was dropped!  Re-broadcasting...
    undefined
    [ERROR] relayer: error attempting to broadcast transaction 0x33aa247d292c1a41ffda4e219e243c5ea9f3ce647081481bc501a39f143a21ff
    [ERROR] relayer: Error: known transaction: 33aa247d292c1a41ffda4e219e243c5ea9f3ce647081481bc501a39f143a21ff
        at web3Inst.currentProvider.send (/app/infra/relayer/src/util.js:51:22)
        at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/src/index.js:77:13)
        at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:64:18)
        at XMLHttpRequest._setReadyState (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:354:12)
        at XMLHttpRequest._onHttpResponseEnd (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:509:12)
        at IncomingMessage.<anonymous> (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:469:24)
        at IncomingMessage.emit (events.js:203:15)
        at endReadableNT (_stream_readable.js:1129:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)

~~This looks like maybe the tx was created with a bad nonce(already used).  Not 100% on that yet.~~  This appears to be an intermittent issue.  Will add some instrumentation so we can inspect the tx object that caused it

**Comment by mikeshultz** [comment]
Sent to Alchemy since it appears this is only occurring because we have pending transactions that aren't returning with `eth_getTransactionByHash`.  The transactions also appear to have been set for the distant future due to the bug addressed by #2534 

Going to close this as basically a non-issue in this case since the error was handled, logged, and the bug that caused it should be fixed now.
