### ISSUE TITLE
Error with ProxyCreation event handling

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2622]
I think this is the result of those error transactions I saw.  The "out of gas but not reverted" ones, where `create2` returns `0`, which fires the event with `0`.  Might want to handle these better in the listener since they are officially on the chain for all of time.

    [ERROR] event-listener: Error: Invalid proxy address in ProxyCreation event: 0x0000000000000000000000000000000000000000
        at ProxyEventHandler.process (/app/infra/discovery/src/listener/handler_proxy.js:41:13)
        at withRetrys (/app/infra/discovery/src/listener/handler.js:90:30)
        at withRetrys (/app/infra/discovery/src/listener/utils.js:78:20)
        at handleEvent (/app/infra/discovery/src/listener/handler.js:89:11)
        at process._tickCallback (internal/process/next_tick.js:68:7) 'will retry in 0.103 seconds, retry count 0'

cc: @franckc @nick

**Comment by mikeshultz** [comment]
Marking this P1 just because every time the listener is started it'll essentially delay the processing of recent events.

**Comment by franckc** [comment]
When the listener restarts, it does not reprocess all events from epoch. It resumes at whatever last block with an event was processed (based on cursor saved in the "listener" DB table). Therefore this event with bad data should not delay the restart of the processor in the future.

So I don't think this is necessarily an issue we need to worry about ?

**Comment by mikeshultz** [comment]
ah, good point.  Could drop down the priority.  Should still probably be handled though.
