### ISSUE TITLE
Purse: 500 caused invalid state

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2663]
Looks like all accounts are stuck in an invalid state, and saw this in the logs:

    [ERROR] relayer: Transaction failure: Error: Invalid JSON RPC response: "<h1>Server Error (500)</h1>"
        at Object.InvalidResponse (/app/node_modules/web3-core-helpers/src/errors.js:42:16)
        at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/src/index.js:73:32)
        at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:64:18)
        at XMLHttpRequest._setReadyState (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:354:12)
        at XMLHttpRequest._onHttpResponseEnd (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:509:12)
        at IncomingMessage.<anonymous> (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:469:24)
        at IncomingMessage.emit (events.js:203:15)
        at endReadableNT (_stream_readable.js:1129:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)

5/6 appear to be transactions related to #2662.  Could be a cause of that issue?  Does the dapp rely on the DB and relayer confirming these transactions to know if a proxy exists?

**Comment by mikeshultz** [comment]
Also found in the logs.  This appears to be the first error:

    [ERROR] - 2019-07-08T14:21:30.619772428Z - (node:78) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
        at Object.InvalidResponse (/app/node_modules/web3-core-helpers/src/errors.js:42:16)
        at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/src/index.js:73:32)
        at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:64:18)
        at XMLHttpRequest._setReadyState (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:354:12)
        at XMLHttpRequest._onHttpResponseEnd (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:509:12)
        at IncomingMessage.<anonymous> (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:469:24)
        at IncomingMessage.emit (events.js:203:15)
        at endReadableNT (_stream_readable.js:1129:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    [ERROR] - 2019-07-08T14:21:30.619875640Z - (node:78) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    [ERROR] - 2019-07-08T14:21:30.619881563Z - (node:78) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mikeshultz** [comment]
And this:

    [INFO] - 2019-07-08T14:45:48.260031065Z - ESC[31;22m[ERROR] ESC[39;1mrelayerESC[0m: Transaction failure: Error: Invalid JSON RPC response: ""
        at Object.InvalidResponse (/app/node_modules/web3-core-helpers/src/errors.js:42:16)
        at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/src/index.js:73:32)
        at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:64:18)
        at XMLHttpRequest._setReadyState (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:354:12)
        at XMLHttpRequest._onHttpResponseEnd (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:509:12)
        at IncomingMessage.<anonymous> (/app/node_modules/web3-providers-http/node_modules/xhr2/lib/xhr2.js:469:24)
        at IncomingMessage.emit (events.js:203:15)
        at endReadableNT (_stream_readable.js:1129:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by mikeshultz** [comment]
None of these happened at about the time `_process()` appears to have locked/died.  It's really unclear how it went from ticking away happily to just not doing anything.  My money is on the unhandled promise rejection, but it happens way before it appears that Promise has died.  Will add some instrumentation and some more defensive try/catch blocks...

**Comment by mikeshultz** [comment]
PR #2667 has been merged to help diagnose this issue.

**Comment by mikeshultz** [comment]
Actually, I'm going to close this.  These errors from Alchemy are all now handled from the above PR and the process no longer crashes and shouldn't reach this invalid state.
