### ISSUE TITLE
Relayer: Error updating transaction

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2669]
Seen in the logs just now:

    [ERROR] relayer: { SequelizeDatabaseError: value "5000000000" is out of range for type integer
        at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:354:16)
        at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:71:18)
        at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)
        at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)
        at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)
        at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:695:18)
        at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
        at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
        at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
      name: 'SequelizeDatabaseError',
      parent:
       { error: value "5000000000" is out of range for type integer
           at Connection.parseE (/app/node_modules/pg/lib/connection.js:602:11)
           at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:399:19)
           at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:121:22)
           at Socket.emit (events.js:198:13)
           at addChunk (_stream_readable.js:288:12)
           at readableAddChunk (_stream_readable.js:269:11)
           at Socket.Readable.push (_stream_readable.js:224:10)
           at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
         name: 'error',
         length: 104,
         severity: 'ERROR',
         code: '22003',
         detail: undefined,
         hint: undefined,
         position: undefined,
         internalPosition: undefined,
         internalQuery: undefined,
         where: undefined,
         schema: undefined,
         table: undefined,
         column: undefined,
         dataType: undefined,
         constraint: undefined,
         file: 'numutils.c',
         line: '75',
         routine: 'pg_atoi',
         sql:
          'UPDATE "relayer_txn" SET "tx_hash"=$1,"gas_price"=$2,"updated_at"=$3 WHERE "id" = $4' },
      original:
       { error: value "5000000000" is out of range for type integer
           at Connection.parseE (/app/node_modules/pg/lib/connection.js:602:11)
           at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:399:19)
           at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:121:22)
           at Socket.emit (events.js:198:13)
           at addChunk (_stream_readable.js:288:12)
           at readableAddChunk (_stream_readable.js:269:11)
           at Socket.Readable.push (_stream_readable.js:224:10)
           at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
         name: 'error',
         length: 104,
         severity: 'ERROR',
         code: '22003',
         detail: undefined,
         hint: undefined,
         position: undefined,
         internalPosition: undefined,
         internalQuery: undefined,
         where: undefined,
         schema: undefined,
         table: undefined,
         column: undefined,
         dataType: undefined,
         constraint: undefined,
         file: 'numutils.c',
         line: '75',
         routine: 'pg_atoi',
         sql:
          'UPDATE "relayer_txn" SET "tx_hash"=$1,"gas_price"=$2,"updated_at"=$3 WHERE "id" = $4' },
      sql:
       'UPDATE "relayer_txn" SET "tx_hash"=$1,"gas_price"=$2,"updated_at"=$3 WHERE "id" = $4' }

Probably related to PR #2657. 

cc @franckc

**Comment by mikeshultz** [comment]
Closed by #2670
