### ISSUE TITLE
Null address on local docker setup

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2869]
graphql           | Error: Provided address "null" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.
    graphql           |     at Method.inputAddressFormatter (/app/node_modules/web3-core-helpers/src/formatters.js:402:11)
    graphql           |     at /app/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:144:38
    graphql           |     at Array.map (<anonymous>)
    graphql           |     at Method.formatInput (/app/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:142:32)
    graphql           |     at Method.toPayload (/app/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:177:23)
    graphql           |     at Eth.send [as getCode] (/app/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:469:30)
    graphql           |     at getCode (/app/packages/graphql/src/contracts.js:53:31)
    graphql           |     at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:45:40)
    graphql           |     at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:271:22)
    graphql           |     at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:97:21)
    graphql           |     at asyncGeneratorStep (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    graphql           |     at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    graphql           |     at /app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    graphql           |     at new Promise (<anonymous>)
    graphql           |     at /app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    graphql           |     at isValidContract (/app/packages/graphql/src/contracts.js:84:27)
    graphql           |     at isValidContract (/app/packages/graphql/src/contracts.js:350:7)
    graphql           |     at Object.<anonymous> (/app/packages/graphql/src/server.js:10:1)
    graphql           |     at Module._compile (internal/modules/cjs/loader.js:776:30)
    graphql           |     at Module._compile (/app/node_modules/pirates/lib/index.js:99:24)
    graphql           |     at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    graphql           |     at Object.newLoader [as .js] (/app/node_modules/pirates/lib/index.js:104:7)

**Comment by mikeshultz** [comment]
Appears to be that `IdentityProxyImplementation` address is missing for docker config.
