### ISSUE TITLE
[bridge] Crash in twitter request verification

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2883]
Seeing this in the production bridge logs:
```
2019-08-06T22:32:37.933914738Z RangeError [ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH]: Input buffers must have the same length
2019-08-06T22:32:37.934002592Z     at Object.timingSafeEqual (internal/crypto/util.js:80:11)
2019-08-06T22:32:37.934009298Z     at verifyRequestSignature (/app/infra/bridge/src/controllers/hooks/index.js:161:24)
```

**Comment by franckc** [comment]
Temporarily disabled this code in
https://github.com/OriginProtocol/origin/commit/63ccbec6a497c28e1a5af2a8c2ab3e38664b9f37

**Comment by franckc** [comment]
CC @sparrowDom

**Comment by franckc** [comment]
Logs from the bridge after I added instrumentation to log the value of the sign and token parameters:
`2019-08-06T23:25:18.335539837Z [DEBUG] origin-bridge: sign:sha256=EhGhUS7XZMCbzZkJmKerYVXfNo9MZ51c7QzDNE33n/s= token:MzQ4q5xmWFeykffw55R4uC6xfeUCegKFcA5Cd+/VBrE=`
