### ISSUE TITLE
Growth cron error

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2898]
Seen in the wild:

    [ERROR] cron: Job failed:  Error: A campaign id must be supplied
        at VerifyEvents.process (/app/infra/growth/src/scripts/verifyEvents.js:40:13)
        at GrowthVerifyEventsJob (/app/infra/cron/src/jobs/growthVerifyEvents.js:18:20)
        at processor (/app/node_modules/bull/lib/process/master.js:47:50)
        at process.on.msg (/app/node_modules/bull/lib/process/master.js:64:23)
        at process.emit (events.js:198:13)
        at emit (internal/child_process.js:832:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)

cc: @franckc

**Comment by franckc** [comment]
Fixed in https://github.com/OriginProtocol/origin/commit/6e6dd2b72fd5c2b047550f8f98f76d903170b765
