### ISSUE TITLE
Cannot query field "contractAddr" on type "Listing".

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#3066]
Seen the following response on master on the AllListings query sent to prod graphql server:

    {
        "errors": [{
            "message": "Cannot query field \"contractAddr\" on type \"Listing\".",
            "locations": [{
                "line": 23,
                "column": 3
            }],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": ["GraphQLError: Cannot query field \"contractAddr\" on type \"Listing\".", "    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)", "    at Object.enter (/app/node_modules/graphql/language/visitor.js:324:29)", "    at Object.enter (/app/node_modules/graphql/language/visitor.js:375:25)", "    at visit (/app/node_modules/graphql/language/visitor.js:242:26)", "    at Object.validate (/app/node_modules/graphql/validation/validate.js:54:22)", "    at validate (/app/node_modules/apollo-server-core/src/requestPipeline.ts:426:22)", "    at Object.<anonymous> (/app/node_modules/apollo-server-core/src/requestPipeline.ts:250:32)", "    at Generator.next (<anonymous>)", "    at fulfilled (/app/node_modules/apollo-server-core/dist/requestPipeline.js:4:58)", "    at process._tickCallback (internal/process/next_tick.js:68:7)"]
                }
            }
        }]
    }

Query:

    {"operationName":"AllListings","variables":{"first":10,"sort":null,"order":null,"search":"","filters":[{"name":"status","value":"active","valueType":"STRING","operator":"EQUALS"}]},"query":"query AllListings($first: Int, $after: String, $sort: String, $order: String, $search: String, $filters: [ListingFilterInput!], $listingIds: [String]) {
      marketplace {
        listings(first: $first, after: $after, sort: $sort, order: $order, search: $search, filters: $filters, listingIds: $listingIds) {
          totalCount
          pageInfo {
            hasNextPage
            hasPreviousPage
            endCursor
            __typename
          }
          nodes {
            ...basicListingFields
            __typename
          }
          __typename
        }
        __typename
      }
    }

    fragment basicListingFields on Listing {
      id
      contractAddr
      valid
      validationError
      status
      totalEvents
      seller {
        id
        __typename
      }
      arbitrator {
        id
        __typename
      }
      deposit
      depositAvailable
      createdEvent {
        timestamp
        __typename
      }
      pendingBuyers {
        id
        __typename
      }
      category
      categoryStr
      subCategory
      title
      description
      currencyId
      price {
        amount
        currency {
          ... on Currency {
            id
            __typename
          }
          __typename
        }
        __typename
      }
      acceptedTokens {
        id
        __typename
      }
      media {
        url
        urlExpanded
        contentType
        __typename
      }
      commission
      commissionPerUnit
      ... on UnitListing {
        unitsTotal
        unitsAvailable
        unitsSold
        unitsPending
        multiUnit
        __typename
      }
      ... on ServiceListing {
        unitsSold
        unitsPending
        unitsAvailable
        __typename
      }
      ... on FractionalListing {
        weekendPrice {
          amount
          currency {
            ... on Currency {
              id
              __typename
            }
            __typename
          }
          __typename
        }
        booked
        customPricing
        unavailable
        __typename
      }
      ... on FractionalHourlyListing {
        timeZone
        workingHours
        booked
        customPricing
        unavailable
        __typename
      }
      ... on GiftCardListing {
        unitsTotal
        unitsAvailable
        unitsSold
        unitsPending
        multiUnit
        retailer
        cardAmount
        issuingCountry
        isDigital
        isCashPurchase
        receiptAvailable
        __typename
      }
      __typename
    }
    "}

**Comment by mikeshultz** [comment]
Prod just isn't up to date yet.
