### ISSUE TITLE
id.split is not a function

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#3067]
Seen on dev:

    ERROR: {
        "message": "id.split is not a function",
        "locations": [
            {
                "line": 3,
                "column": 5
            }
        ],
        "path": [
            "marketplace",
            "listings"
        ],
        "extensions": {
            "code": "INTERNAL_SERVER_ERROR",
            "exception": {
                "stacktrace": [
                    "TypeError: id.split is not a function",
                    "    at split (/app/packages/graphql/src/resolvers/marketplace/listings.js:85:28)",
                    "    at Array.map (<anonymous>)",
                    "    at map (/app/packages/graphql/src/resolvers/marketplace/listings.js:84:11)",
                    "    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:45:40)",
                    "    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:271:22)",
                    "    at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:97:21)",
                    "    at asyncGeneratorStep (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)",
                    "    at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)",
                    "    at /app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7",
                    "    at new Promise (<anonymous>)",
                    "    at /app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12",
                    "    at resultsFromIds (/app/packages/graphql/src/resolvers/marketplace/listings.js:147:26)",
                    "    at resultsFromIds (/app/packages/graphql/src/resolvers/marketplace/listings.js:187:16)",
                    "    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:45:40)",
                    "    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:271:22)",
                    "    at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:97:21)",
                    "    at asyncGeneratorStep (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)",
                    "    at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)",
                    "    at process._tickCallback (internal/process/next_tick.js:68:7)"
                ]
            }
        }
    }

**Comment by mikeshultz** [comment]
It appears @nick already fixed this.
