### ISSUE TITLE
Rinkeby OGN faucet is broken

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3231]
https://faucet.originprotocol.com/ returns an internal server error when OGN is requested.

Server logs show: 
```
Network=4 Url=https://eth-rinkeby.alchemyapi.io/jsonrpc/[redacted] Mnemonic=[redacted]
[DEBUG] faucet: TokenDistributor config: networkId=4 contractAddress=0xa115e16ef6e217f7a327a57031f75ce0487aadb8
[INFO]  faucet: Hotwallet address:  0x1E3844b4752172B6E85F390E2DF4FfC4D63425f9
Origin faucet app listening on port 5000!
Error: Invalid JSON RPC response: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n</body></html>\n"
    at Object.InvalidResponse (/app/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/app/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequest.dispatchEvent (/app/node_modules/xhr2/lib/xhr2.js:76:20)
    at XMLHttpRequest._setReadyState (/app/node_modules/xhr2/lib/xhr2.js:422:14)
    at XMLHttpRequest._onHttpResponseEnd (/app/node_modules/xhr2/lib/xhr2.js:615:14)
    at IncomingMessage._response.on (/app/node_modules/xhr2/lib/xhr2.js:567:23)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
```

**Comment by tomlinton** [comment]
I think you fixed this right @franckc? I used it today and it worked.

**Comment by micahalcorn** [comment]
Same here ✅

**Comment by franckc** [comment]
Love it. No I did not do any code change. So perhaps just the container getting restarted during a deploy fixed it :)
