### ISSUE TITLE
Purchase crash - Error: GraphQL error: can not decode uint256 from ABI: 0x

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3266]
Purchasing a listing on Rinkeby intermittently fails for me.
Config:
 - iOS
 - Origin mobile app v0.22.0
 - Rinkeby
 - Account 0xD85A569F3C26f81070544451131c742283360400

Screenshot:
![image0](https://user-images.githubusercontent.com/945910/64469933-9d84d480-d0ef-11e9-8f64-f500928e8cdd.png)

**Comment by micahalcorn** [comment]
Related to https://github.com/OriginProtocol/origin/issues/3069 or no? 🤔

**Comment by franckc** [comment]
Potentially could be similar type of issue.
Though #3069 happened on graphql server side while the error reported here happened on client side (I did check graphql staging logs and they were clean)...

**Comment by mikeshultz** [comment]
Having a hard time getting viability into this error.  The marketplace errors aren't output to the console, so I'm getting nothing from the mobile debug console.  @tomlinton any ideas?

Has anyone by chance seen this on desktop?

**Comment by mikeshultz** [comment]
Added #3273 which will report this to sentry.  No guarantees we'll get more useful information, but hopefully more visibility than I'm getting now.

**Comment by mikeshultz** [comment]
{
      "arguments": [{
        "graphQLErrors": "[\"[Object]\"]",
        "name": "Error",
        "extraInfo": "[undefined]",
        "networkError": null,
        "message": "GraphQL error: Couldn't decode uint256 from ABI: 0x",
        "stack": "Error: GraphQL error: Couldn't decode uint256 from ABI: 0x
        at new t (https://dapp.staging.originprotocol.com/app.42fbee55.js:179:35942)
        at Object.next (https://dapp.staging.originprotocol.com/app.42fbee55.js:179:52595)
        at b (https://dapp.staging.originprotocol.com/app.42fbee55.js:105:5935)
        at v (https://dapp.staging.originprotocol.com/app.42fbee55.js:105:6439)
        at e.value (https://dapp.staging.originprotocol.com/app.42fbee55.js:105:6992)
        at https://dapp.staging.originprotocol.com/app.42fbee55.js:179:50216
        at Set.forEach (<anonymous>)
        at Object.next (https://dapp.staging.originprotocol.com/app.42fbee55.js:179:50179)
        at b (https://dapp.staging.originprotocol.com/app.42fbee55.js:105:5935)
        at v (https://dapp.staging.originprotocol.com/app.42fbee55.js:105:6439)
        at e.value (https://dapp.staging.originprotocol.com/app.42fbee55.js:105:6992)
        at https://dapp.staging.originprotocol.com/app.42fbee55.js:179:96630"
      }]
    }

**Comment by mikeshultz** [comment]
Interesting note in the breadcrumbs is that there are infura calls.

**Comment by mikeshultz** [comment]
Error: GraphQL error: Couldn't decode uint256 from ABI: 0x
      at new t(/app/node_modules/apollo-client/bundle.esm.js:63:28)
      at call(/app/node_modules/apollo-client/bundle.esm.js:1003:53)
      at notifySubscription(/app/node_modules/zen-observable/lib/Observable.js:130:18)
      at onNotify(/app/node_modules/zen-observable/lib/Observable.js:165:3)
      at next(/app/node_modules/zen-observable/lib/Observable.js:219:7)
      at ? (/app/node_modules/apollo-client/bundle.esm.js:865:75)
      at Set.forEach(<anonymous>)
      at call(/app/node_modules/apollo-client/bundle.esm.js:865:27)
      at notifySubscription(/app/node_modules/zen-observable/lib/Observable.js:130:18)
      at onNotify(/app/node_modules/zen-observable/lib/Observable.js:165:3)
      at next(/app/node_modules/zen-observable/lib/Observable.js:219:7)
      at ? (/app/node_modules/apollo-link-schema/lib/bundle.esm.js:23:30)

**Comment by mikeshultz** [comment]
Possibly related: #3275

**Comment by mikeshultz** [comment]
PR #3279 should take care of this.  Though it's still not exactly clear why or how web3-provider conflicts with mobile bridge.

**Comment by micahalcorn** [comment]
It looks like [Holly might have just hit this](https://sentry.io/organizations/origin-protocol/issues/1098412085/events/f8aedd737c3447799e9c7e87371e637c/). 🇨🇳

**Comment by mikeshultz** [comment]
That looks different, @micahalcorn.  Not sure why sentry is grouping them?

**Comment by mikeshultz** [comment]
@franckc have you seen this since PR #3279?

**Comment by franckc** [comment]
@mikeshultz No I haven't seen it during my testing recently...

**Comment by mikeshultz** [comment]
I'm calling it.  We can reopen if needed.  For some reason, the linked Sentry error now appears to be something else entirely. :man_shrugging:
