### ISSUE TITLE
Bridge telegram error on staging

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#3281]
saw this in the logs recently on staging:

    TypeError: Cannot read property 'text' of undefined
        at router.post (/app/infra/bridge/src/controllers/hooks/telegram.js:43:15)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at next (/app/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at /app/node_modules/express/lib/router/index.js:281:22
        at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
        at next (/app/node_modules/express/lib/router/index.js:275:10)
        at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
        at router (/app/node_modules/express/lib/router/index.js:47:12)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
        at /app/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
        at next (/app/node_modules/express/lib/router/index.js:275:10)
        at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
        at router (/app/node_modules/express/lib/router/index.js:47:12)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
        at /app/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
        at next (/app/node_modules/express/lib/router/index.js:275:10)
        at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
        at router (/app/node_modules/express/lib/router/index.js:47:12)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
        at /app/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
        at next (/app/node_modules/express/lib/router/index.js:275:10)
        at urlencodedParser (/app/node_modules/body-parser/lib/types/urlencoded.js:82:7)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
        at /app/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
        at next (/app/node_modules/express/lib/router/index.js:275:10)
        at jsonParser (/app/node_modules/body-parser/lib/types/json.js:101:7)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
        at /app/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)

**Comment by shahthepro** [comment]
Thanks for reporting this @mikeshultz. I'll take a look at it.

**Comment by franckc** [comment]
I just checked and this is a staging only issue. Does not happen in prod.

**Comment by shahthepro** [comment]
It happened on staging. Looks like Telegram's updates on Webhook doesn't always have `message` in the body payload. Have added a check (and a debug statement) for that in #3667
