### ISSUE TITLE
Messaging server bug

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#3412]
seen in prod:

    (node:136) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://graphql.originprotocol.com/graphql reason: Unexpected token < in JSON at position 0
        at /app/node_modules/node-fetch/lib/index.js:272:32
        at process._tickCallback (internal/process/next_tick.js:68:7)
    (node:136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 372)

**Comment by mikeshultz** [comment]
Since I'm not seeing any explicit graphql queries in the source(unless I missed something), I'm thinking this could be related to the graphql block poller?

**Comment by mikeshultz** [comment]
Connectivity looks okay between messaging and graphql:

    root@prod-messaging-0:/app# curl -X POST -H "Content-Type: application/json" --data '{ "operationName": "BlockNumber", "variables": {}, "query": "query BlockNumber { web3 { blockNumber } }" }' https://graphql.originprotocol.com/graphql
    {"data":{"web3":{"blockNumber":8563217}}}

**Comment by mikeshultz** [comment]
This might be the cause of this Sentry issue:  https://sentry.io/organizations/origin-protocol/issues/1022303570/?project=1402589&query=is%3Aunresolved&statsPeriod=14d

**Comment by mikeshultz** [comment]
Interestingly, seen something similar in the origin-cron container.  Unsure if related:

    (node:80) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://graphql.staging.originprotocol.com/graphql reason: Unexpected token < in JSON at position 0
        at /app/node_modules/node-fetch/lib/index.js:272:32
        at process._tickCallback (internal/process/next_tick.js:68:7)
    (node:80) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 160)

**Comment by mikeshultz** [comment]
I'm cheating and marking this as a p2 since we have no reports of this affecting anything.
