### ISSUE TITLE
Relayer gas station error handling and unwanted account state

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#3417]
Looks like ethgasstation request error handling needs some love.  This also appears to have somehow caused the nonce to not be incremented, resulting in an account being stuck in an unwanted state.

    2019-09-17T12:26:29.393143609Z ESC[36;22m[DEBUG] ESC[39;1mrelayerESC[0m: Sending tx:  { to: '0x7B303bE82c05592fea642671E624cb9795F3767D',
    2019-09-17T12:26:29.393194846Z   data:
    2019-09-17T12:26:29.393199726Z    '0x474fa4940000000000000000000000008ac16c08105de55a02e2b7462b1eec6085fa4d860000000000000000000000000000000000000000000000000000000000000080000000000000000000000000c307ef1e4a1fe9a1e37bf0c25fe864f890aeeaa90
    00000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000414f1b77d03ec7150ff3c1580b953987be50a2e9a70f0de2f5a3b60963b1f503a402b5224c53180eb1df2741bd55d678659278f57f6888388
    05a6db86ee9495d371c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024a30749dfd37e24fb8371d6c1b7ce5ff3c9cbdb758cbb9c2b3adf7daec4399364126afa01000000000000000000000
    00000000000000000000000000000000000',
    2019-09-17T12:26:29.393204855Z   gas: 250000,
    2019-09-17T12:26:29.393208444Z   from: '0x9629F3998d08A7Bc479451bE450e897E3240B2b2',
    2019-09-17T12:26:29.393211823Z   nonce: 9352,
    2019-09-17T12:26:29.393215405Z   gasPrice: <BN: 684ee1800> }
    2019-09-17T12:26:30.060096336Z ESC[32;22m[INFO]  ESC[39;1mrelayerESC[0m: Sent 0x3187dd9b2d495f561060bfb3363b69d518109b5d9073b4509014aef7a1496653
    2019-09-17T12:26:30.060157874Z ESC[32;22m[INFO]  ESC[39;1mrelayerESC[0m: Submitted tx with hash 0x3187dd9b2d495f561060bfb3363b69d518109b5d9073b4509014aef7a1496653 at gas price 28000000000
    2019-09-17T12:26:50.331805577Z ESC[36;22m[DEBUG] ESC[39;1mrelayerESC[0m: Transaction 0x3187dd9b2d495f561060bfb3363b69d518109b5d9073b4509014aef7a1496653 has been mined.
    2019-09-17T12:26:50.3558679Z ESC[32;22m[INFO]  ESC[39;1mrelayerESC[0m: Tx with hash 0x3187dd9b2d495f561060bfb3363b69d518109b5d9073b4509014aef7a1496653 mined. Status: Confirmed. Gas used: 53291.
    2019-09-17T12:26:50.358967486Z ESC[36;22m[DEBUG] ESC[39;1mrelayerESC[0m: Removed 0x3187dd9b2d495f561060bfb3363b69d518109b5d9073b4509014aef7a1496653 from pending
    2019-09-17T12:26:51.606599356Z ESC[33;22m[WARN]  ESC[39;1mrelayerESC[0m: Master account is low @ 0.001512 Ether. Add funds soon!
    2019-09-17T12:26:52.61320889Z ESC[36;22m[DEBUG] ESC[39;1mrelayerESC[0m: Planning to fund 0 child accounts
    2019-09-17T12:27:33.178929249Z Error fetching results from ethgastation.info
    2019-09-17T12:27:33.179992039Z { FetchError: request to https://ethgasstation.info/json/ethgasAPI.json failed, reason: connect ETIMEDOUT 104.31.84.251:443
    2019-09-17T12:27:33.180022938Z     at ClientRequest.<anonymous> (/app/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1393:11)
    2019-09-17T12:27:33.180028722Z     at ClientRequest.emit (events.js:198:13)
    2019-09-17T12:27:33.180033231Z     at ClientRequest.EventEmitter.emit (domain.js:448:20)
    2019-09-17T12:27:33.180037591Z     at TLSSocket.socketErrorListener (_http_client.js:392:9)
    2019-09-17T12:27:33.180041723Z     at TLSSocket.emit (events.js:198:13)
    2019-09-17T12:27:33.180045688Z     at TLSSocket.EventEmitter.emit (domain.js:448:20)
    2019-09-17T12:27:33.180049708Z     at emitErrorNT (internal/streams/destroy.js:91:8)
    2019-09-17T12:27:33.180053807Z     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    2019-09-17T12:27:33.180064904Z     at process._tickCallback (internal/process/next_tick.js:63:19)
    2019-09-17T12:27:33.180070773Z   message:
    2019-09-17T12:27:33.180076565Z    'request to https://ethgasstation.info/json/ethgasAPI.json failed, reason: connect ETIMEDOUT 104.31.84.251:443',
    2019-09-17T12:27:33.180082683Z   type: 'system',
    2019-09-17T12:27:33.180088158Z   errno: 'ETIMEDOUT',
    2019-09-17T12:27:33.180093196Z   code: 'ETIMEDOUT' }
    2019-09-17T12:27:33.674127778Z ESC[36;22m[DEBUG] ESC[39;1mrelayerESC[0m: Sending tx:  { to: '0x7B303bE82c05592fea642671E624cb9795F3767D',
    2019-09-17T12:27:33.674186791Z   data:
    2019-09-17T12:27:33.674193057Z    '0x474fa4940000000000000000000000008ac16c08105de55a02e2b7462b1eec6085fa4d860000000000000000000000000000000000000000000000000000000000000080000000000000000000000000c307ef1e4a1fe9a1e37bf0c25fe864f890aeeaa90
    0000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000041dabf1063c8a54ca62667b42beb2de99a7d644f3d591f9bf7f0b0ff9a7ebc1f821baa961a9a3d5c201987ce949b48f588854cb16813e3ed6
    270a98a7a2d7c5d851c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024a30749df15a7075cbe6c546be33437be1c444a87bb14803f377f712d71562307b205e659000000000000000000000
    00000000000000000000000000000000000',
    2019-09-17T12:27:33.674222798Z   gas: 250000,
    2019-09-17T12:27:33.674226288Z   from: '0x9629F3998d08A7Bc479451bE450e897E3240B2b2',
    2019-09-17T12:27:33.674229694Z   nonce: 9352,
    2019-09-17T12:27:33.674232877Z   gasPrice: <BN: 66720b000> }
    2019-09-17T12:27:34.250893071Z { code: -32010,
    2019-09-17T12:27:34.250939657Z   message: 'Transaction nonce is too low. Try incrementing the nonce.' }
    2019-09-17T12:27:34.252952614Z retrying request method:  eth_sendRawTransaction
    2019-09-17T12:27:34.495451339Z { code: -32010,
    2019-09-17T12:27:34.495495127Z   message: 'Transaction nonce is too low. Try incrementing the nonce.' }

**Comment by mikeshultz** [comment]
Also think this is a duplicate of #3355
