### ISSUE TITLE
Reviews error on dev

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#3712]
Seen on dev with reviews query.  User may have one review or none, I can't remember.

    Error: "GraphQL error: Cannot return null for non-nullable field User.id."
        t bundle.esm.js:63
        getCurrentResult bundle.esm.js:159
        getQueryResult react-hooks.esm.js:245
        getExecuteResult react-hooks.esm.js:71
        execute react-hooks.esm.js:88
        u react-hooks.esm.js:344
        So react-hooks.esm.js:318
        Eo react-hooks.esm.js:353
        ay Reviews.js:20
        React 10
        error react-hooks.esm.js:221
        b Observable.js:134
        v Observable.js:165
        value Observable.js:224
        re bundle.esm.js:434
        re bundle.esm.js:434
        r bundle.esm.js:385
    QueryError.js:6:10
        zl QueryError.js:6
        React 10
        error react-hooks.esm.js:221
        b Observable.js:134
        v Observable.js:165
        value Observable.js:224
        re bundle.esm.js:434
        re bundle.esm.js:434
        r bundle.esm.js:385

Params: 

    {
        "id": "0x50041B6B810AE17261fE4590b0E107fa28A08962",
        "first": 3
    }

Query:

    query Reviews($id: ID!, $first: Int, $after: String) {
        marketplace {
          user(id: $id) {
            id
            reviews(first: $first, after: $after) {
              totalCount
              nodes {
                id
                review
                rating
                reviewer {
                  id
                  account {
                    id
                    identity {
                      id
                      fullName
                      avatarUrlExpanded
                    }
                  }
                }
                listing {
                  ... on Listing {
                    id
                    title
                  }
                }
                event {
                  id
                  timestamp
                }
              }
              pageInfo {
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
              }
            }
          }
        }
      }

URL: https://dapp.dev.originprotocol.com/#/listing/2222-000-2

**Comment by mikeshultz** [comment]
Results when run on playground:

    {
      "errors": [
        {
          "message": "missing trie node b3b172f68297e3e4ce229513c5a3361ba652e5fa31e39aaf870fd6537d012911 (path )",
          "locations": [
            {
              "line": 5,
              "column": 7
            }
          ],
          "path": [
            "marketplace",
            "user",
            "reviews"
          ],
          "extensions": {
            "code": "INTERNAL_SERVER_ERROR",
            "exception": {
              "message": "missing trie node b3b172f68297e3e4ce229513c5a3361ba652e5fa31e39aaf870fd6537d012911 (path )",
              "code": -32603,
              "stacktrace": [
                "GraphQLError: missing trie node b3b172f68297e3e4ce229513c5a3361ba652e5fa31e39aaf870fd6537d012911 (path )",
                "    at locatedError (/app/node_modules/graphql/error/locatedError.js:22:10)",
                "    at handleFieldError (/app/node_modules/graphql/execution/execute.js:549:46)",
                "    at /app/node_modules/graphql/execution/execute.js:538:16"
              ]
            }
          }
        }
      ],
      "data": {
        "marketplace": {
          "user": null
        }
      }
    }
