### ISSUE TITLE
Listener fails to process OfferCreated events

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3940]
The listener is crashing when processing OfferCreated events.
The following stacktrace is found in the logs:
```
[INFO]  event-listener: Processing event: blockNumber=8878583     transactionIndex=147     eventName=OfferCreated
[ERROR] event-listener: { Error: GraphQL error: fetch is not defined
GraphQL error: fetch is not defined
    at new ApolloError (/Users/franck/src/origin/node_modules/apollo-client/bundle.umd.js:92:26)
    at /Users/franck/src/origin/node_modules/apollo-client/bundle.umd.js:1587:34
    at /Users/franck/src/origin/node_modules/apollo-client/bundle.umd.js:2007:15
    at Set.forEach (<anonymous>)
    at /Users/franck/src/origin/node_modules/apollo-client/bundle.umd.js:2005:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/Users/franck/src/origin/node_modules/apollo-client/bundle.umd.js:2003:20)
    at /Users/franck/src/origin/node_modules/apollo-client/bundle.umd.js:2130:19
    at Object.next (/Users/franck/src/origin/node_modules/zen-observable/lib/Observable.js:308:23)
    at notifySubscription (/Users/franck/src/origin/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/franck/src/origin/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.next (/Users/franck/src/origin/node_modules/zen-observable/lib/Observable.js:219:7)
    at /Users/franck/src/origin/node_modules/apollo-client/bundle.umd.js:1101:36
    at Set.forEach (<anonymous>)
    at Object.next (/Users/franck/src/origin/node_modules/apollo-client/bundle.umd.js:1100:21)
    at notifySubscription (/Users/franck/src/origin/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/franck/src/origin/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.next (/Users/franck/src/origin/node_modules/zen-observable/lib/Observable.js:219:7)
    at /Users/franck/src/origin/node_modules/apollo-link-schema/lib/index.js:24:30
```

Note: I haven't confirmed whether this is specific to OfferCreated events or also happens for other type of marketplace event.

The impact is that users won't receive a notification and email when there is activity on a listing they purchased.

**Comment by franckc** [comment]
Fixed.
