### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#4266]
Bunch of test suites throwing this:

    (node:120) UnhandledPromiseRejectionWarning: Error: Given parameter is not bytes: "NOT_UPLOADED"
        at SolidityTypeBytes.formatInputBytes [as _inputFormatter] (/home/circleci/origin/node_modules/web3/node_modules/web3-eth-abi/src/formatters.js:56:15)
        at SolidityTypeBytes.SolidityType.encode (/home/circleci/origin/node_modules/web3/node_modules/web3-eth-abi/src/type.js:188:17)
        at /home/circleci/origin/node_modules/web3/node_modules/web3-eth-abi/src/index.js:255:29
        at Array.map (<anonymous>)
        at ABICoder.encodeParameters (/home/circleci/origin/node_modules/web3/node_modules/web3-eth-abi/src/index.js:254:34)
        at /home/circleci/origin/node_modules/web3/node_modules/web3-eth-contract/src/index.js:420:24
        at Array.map (<anonymous>)
        at Object._encodeMethodABI (/home/circleci/origin/node_modules/web3/node_modules/web3-eth-contract/src/index.js:419:12)
        at Object._processExecuteArguments (/home/circleci/origin/node_modules/web3/node_modules/web3-eth-contract/src/index.js:735:39)
        at Object.send (/home/circleci/origin/node_modules/web3/node_modules/web3-eth-contract/src/index.js:760:54)
        at _callee22$ (/home/circleci/origin/packages/graphql/src/mutations/_txHelper.js:573:13)
        at tryCatch (/home/circleci/origin/node_modules/regenerator-runtime/runtime.js:45:40)
        at Generator.invoke [as _invoke] (/home/circleci/origin/node_modules/regenerator-runtime/runtime.js:271:22)
        at Generator.prototype.(anonymous function) [as next] (/home/circleci/origin/node_modules/regenerator-runtime/runtime.js:97:21)
        at asyncGeneratorStep (/home/circleci/origin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
        at _next (/home/circleci/origin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
        at /home/circleci/origin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
        at new Promise (<anonymous>)
        at /home/circleci/origin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12

**Comment by mikeshultz** [comment]
Related: https://github.com/OriginProtocol/origin/blob/f9a111cf1db14e614d7bf395232fae9bbad06a78/packages/graphql/src/mutations/identity/deployIdentity.js#L151

@franckc seems somewhat related to your IPFS changes

**Comment by franckc** [comment]
ah yes. sorry. I'll fix when I have a minute...

**Comment by jonathansampson** [comment]
I did a fresh pull (now on master 186c39138), and I am still seeing this when I run `yarn start` from within `dapps/shop`:

```
PS D:\GitHub\origin-store\dapps\shop> yarn start
yarn run v1.21.1
$ node -r @babel/register index
Starting ganache...
Ganache listening on port 8545.
Start IPFS
Swarm listening on /p2p-circuit/ipfs/QmVo32nSzvvhgw4LT6fKgTwBUYA8XbuReonEMZYF2LgJQR
Started IPFS
Deploying contracts...
Connecting to network test
🚀  Populate GraphQL server ready at http://localhost:4000/
Using NodeAccount 0x0d1d4e623D10F9FBA5Db95830F7d3839406C6AF2
Disabled MetaMask
Imported wallets
Sent eth to Admin
Deployed Origin token to 0xF426505ac145abE033fE77C666840063757Be9cd
Deployed DAI stablecoin to 0x9d075ae44D859191C121d7522da0Cc3B104b8837
Deployed OKB token to 0xd8672a4A1bf37D36beF74E36edb4f17845E76F4e
Deployed Tether to 0x51815CEbeF59b88DAfD1a5f24095eee1236ffCDd
Deployed marketplace v1 to 0x66078a97Def9d40B2cA7abb44733dD897Ec6231D
Added affiliate to marketplace v1
Deployed marketplace v0 to 0xdE5bb8B8961fAef05b2ab38A70C81BdBC91Add29
Added affiliate to marketplace v0
Sent eth to Relayer master account(0xFD5cf8Ec89aF8F4dA1371d40D50A625F3634B743)
Deployed Proxy Factory to 0xa43bD34038Ca13e7115e16770D722E62ea706212
Deployed Identity Proxy imp to 0x12104CB63B58fD9Ed06034052A4C8D268f5D9125
Sent eth to seller
Sent ogn to seller
Set seller token allowance
Sent eth to buyer
Sent DAI to buyer
Set buyer dai token allowance
Sent OKB to buyer
Set buyer OKB token allowance
Sent USDT to buyer
Set buyer USDT token allowance
Sent eth to arbitrator
Sent eth to affiliate
Deployed Identity Events contract to 0x9fD9828a17ef3402540E9D53e25b7e785021Dc6E
(node:98300) UnhandledPromiseRejectionWarning: Error: Given parameter is not bytes: "NOT_UPLOADED"
    at SolidityTypeBytes.formatInputBytes [as _inputFormatter] (D:\GitHub\origin-store\node_modules\web3\node_modules\web3-eth-abi\src\formatters.js:56:15)
    at SolidityTypeBytes.SolidityType.encode (D:\GitHub\origin-store\node_modules\web3\node_modules\web3-eth-abi\src\type.js:188:17)
    at D:\GitHub\origin-store\node_modules\web3\node_modules\web3-eth-abi\src\index.js:255:29
    at Array.map (<anonymous>)
    at ABICoder.encodeParameters (D:\GitHub\origin-store\node_modules\web3\node_modules\web3-eth-abi\src\index.js:254:34)
    at D:\GitHub\origin-store\node_modules\web3\node_modules\web3-eth-contract\src\index.js:420:24
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (D:\GitHub\origin-store\node_modules\web3\node_modules\web3-eth-contract\src\index.js:419:12)
    at Object._processExecuteArguments (D:\GitHub\origin-store\node_modules\web3\node_modules\web3-eth-contract\src\index.js:735:39)
    at Object.send (D:\GitHub\origin-store\node_modules\web3\node_modules\web3-eth-contract\src\index.js:760:54)
    at _callee22$ (D:\GitHub\origin-store\packages\graphql\src\mutations/_txHelper.js:573:13)
    at tryCatch (D:\GitHub\origin-store\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (D:\GitHub\origin-store\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (D:\GitHub\origin-store\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (D:\GitHub\origin-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\GitHub\origin-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\GitHub\origin-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\GitHub\origin-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at sendViaWeb3 (D:\GitHub\origin-store\packages\graphql\src\mutations\_txHelper.js:1103:22)
    at _callee4$ (D:\GitHub\origin-store\packages\graphql\src\mutations/_txHelper.js:784:11)
    at tryCatch (D:\GitHub\origin-store\node_modules\regenerator-runtime\runtime.js:45:40)
(node:98300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:98300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by franckc** [comment]
@jonathansampson Ah yes good catch! Thanks for reporting this. I'll fix it. In the meantime if that blocks you for your local development, update the code to have the IPFS hash uploaded regardless of the environment: https://github.com/OriginProtocol/origin/blob/master/packages/graphql/src/mutations/identity/deployIdentity.js#L153

**Comment by franckc** [comment]
Should be fixed now.
